-- Wave 39: evolve the existing consequence inbox into a durable observation
-- channel.  Legacy act-emitted consequences retain their physical rows and
-- nullable provenance.  Canonical observations are externally reduced,
-- immutable evidence and never become subjective memories on ingestion.

ALTER TABLE cognitive_consequences
    ALTER COLUMN act_id DROP NOT NULL;
ALTER TABLE cognitive_consequences
    ALTER COLUMN ordinal DROP NOT NULL;

ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS source_id text;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS source_stream text;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS source_sequence bigint;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS observation_key text;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS difference_kind text;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS reducer_name text;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS reducer_version text;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS payload_hash text;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS salience real;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS confidence real;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS source_observed_at timestamptz;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS declared_action_host_key text;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS declared_action_ordinal integer;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS declared_action_event_id text;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS action_act_id uuid;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS correlation_status text NOT NULL DEFAULT 'legacy';
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS ingest_seq bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE cognitive_consequences
    ADD COLUMN IF NOT EXISTS late boolean NOT NULL DEFAULT false;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'cognitive_observations_action_act_fk'
          AND conrelid = 'cognitive_consequences'::regclass
    ) THEN
        ALTER TABLE cognitive_consequences
            ADD CONSTRAINT cognitive_observations_action_act_fk
            FOREIGN KEY (action_act_id, agent_id)
            REFERENCES cognitive_acts(id, agent_id)
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'cognitive_observations_source_shape_check'
          AND conrelid = 'cognitive_consequences'::regclass
    ) THEN
        ALTER TABLE cognitive_consequences
            ADD CONSTRAINT cognitive_observations_source_shape_check CHECK (
                source_id IS NULL OR (
                    act_id IS NULL AND ordinal IS NULL AND
                    length(source_id) BETWEEN 1 AND 256 AND
                    source_stream IS NOT NULL AND
                    length(source_stream) BETWEEN 1 AND 256 AND
                    source_sequence IS NOT NULL AND source_sequence >= 0 AND
                    observation_key IS NOT NULL AND
                    length(observation_key) BETWEEN 1 AND 256 AND
                    difference_kind IN (
                        'state_change', 'delivery_receipt', 'action_result',
                        'action_error', 'external_signal'
                    ) AND kind = difference_kind AND
                    length(content) BETWEEN 1 AND 2000 AND
                    reducer_name IS NOT NULL AND
                    length(reducer_name) BETWEEN 1 AND 128 AND
                    reducer_version IS NOT NULL AND
                    length(reducer_version) BETWEEN 1 AND 64 AND
                    payload_hash ~ '^[0-9a-f]{64}$' AND
                    salience IS NOT NULL AND salience BETWEEN 0 AND 1 AND
                    confidence IS NOT NULL AND confidence BETWEEN 0 AND 1
                )
            );
    END IF;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'cognitive_observations_action_shape_check'
          AND conrelid = 'cognitive_consequences'::regclass
    ) THEN
        ALTER TABLE cognitive_consequences
            ADD CONSTRAINT cognitive_observations_action_shape_check CHECK (
                source_id IS NULL OR (
                    correlation_status IN (
                        'uncorrelated', 'pending', 'resolved', 'conflict'
                    ) AND
                    (
                        (declared_action_host_key IS NULL AND
                         declared_action_ordinal IS NULL AND
                         declared_action_event_id IS NULL AND
                         action_act_id IS NULL AND
                         correlation_status = 'uncorrelated')
                        OR
                        (declared_action_host_key IS NOT NULL AND
                         length(declared_action_host_key) BETWEEN 1 AND 512 AND
                         (declared_action_ordinal IS NOT NULL OR
                          declared_action_event_id IS NOT NULL) AND
                         (declared_action_ordinal IS NULL OR
                          declared_action_ordinal >= 0) AND
                         (declared_action_event_id IS NULL OR
                          length(declared_action_event_id) BETWEEN 1 AND 256) AND
                         (
                             (correlation_status = 'resolved' AND
                              action_act_id IS NOT NULL)
                             OR
                             (correlation_status <> 'resolved' AND
                              action_act_id IS NULL)
                         ))
                    )
                )
            );
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS cognitive_observations_source_key_uq
    ON cognitive_consequences(agent_id, source_id, observation_key)
    WHERE source_id IS NOT NULL AND observation_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS cognitive_observations_source_sequence_uq
    ON cognitive_consequences(agent_id, source_id, source_stream, source_sequence)
    WHERE source_id IS NOT NULL AND source_sequence IS NOT NULL;
CREATE INDEX IF NOT EXISTS cognitive_observations_pending_order_idx
    ON cognitive_consequences(
        agent_id, status, source_id, source_stream, source_sequence, ingest_seq
    ) WHERE status <> 'acknowledged';
CREATE INDEX IF NOT EXISTS cognitive_observations_pending_correlation_idx
    ON cognitive_consequences(agent_id, declared_action_host_key, ingest_seq)
    WHERE source_id IS NOT NULL AND correlation_status = 'pending';

CREATE OR REPLACE FUNCTION styx_immutable_observation_source()
RETURNS trigger AS $$
BEGIN
    IF OLD.source_id IS NOT NULL AND (
        NEW.agent_id IS DISTINCT FROM OLD.agent_id OR
        NEW.source_id IS DISTINCT FROM OLD.source_id OR
        NEW.source_stream IS DISTINCT FROM OLD.source_stream OR
        NEW.source_sequence IS DISTINCT FROM OLD.source_sequence OR
        NEW.observation_key IS DISTINCT FROM OLD.observation_key OR
        NEW.difference_kind IS DISTINCT FROM OLD.difference_kind OR
        NEW.kind IS DISTINCT FROM OLD.kind OR
        NEW.content IS DISTINCT FROM OLD.content OR
        NEW.metadata IS DISTINCT FROM OLD.metadata OR
        NEW.reducer_name IS DISTINCT FROM OLD.reducer_name OR
        NEW.reducer_version IS DISTINCT FROM OLD.reducer_version OR
        NEW.payload_hash IS DISTINCT FROM OLD.payload_hash OR
        NEW.salience IS DISTINCT FROM OLD.salience OR
        NEW.confidence IS DISTINCT FROM OLD.confidence OR
        NEW.source_observed_at IS DISTINCT FROM OLD.source_observed_at OR
        NEW.declared_action_host_key IS DISTINCT FROM OLD.declared_action_host_key OR
        NEW.declared_action_ordinal IS DISTINCT FROM OLD.declared_action_ordinal OR
        NEW.declared_action_event_id IS DISTINCT FROM OLD.declared_action_event_id OR
        NEW.ingest_seq IS DISTINCT FROM OLD.ingest_seq OR
        NEW.late IS DISTINCT FROM OLD.late
    ) THEN
        RAISE EXCEPTION 'canonical observation source payload is immutable'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS cognitive_observations_immutable_source
    ON cognitive_consequences;
CREATE TRIGGER cognitive_observations_immutable_source
BEFORE UPDATE ON cognitive_consequences
FOR EACH ROW EXECUTE FUNCTION styx_immutable_observation_source();

ALTER TABLE cognitive_presentations
    ADD COLUMN IF NOT EXISTS presented_payload jsonb;
ALTER TABLE cognitive_presentations
    ADD COLUMN IF NOT EXISTS payload_hash text;
ALTER TABLE cognitive_presentations
    ADD COLUMN IF NOT EXISTS presentation_version text;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'cognitive_presentations_frozen_shape_check'
          AND conrelid = 'cognitive_presentations'::regclass
    ) THEN
        ALTER TABLE cognitive_presentations
            ADD CONSTRAINT cognitive_presentations_frozen_shape_check CHECK (
                (presented_payload IS NULL AND payload_hash IS NULL AND
                 presentation_version IS NULL)
                OR
                (presented_payload IS NOT NULL AND
                 payload_hash ~ '^[0-9a-f]{64}$' AND
                 presentation_version = 'observation_presentation_v1')
            );
    END IF;
END $$;

CREATE OR REPLACE FUNCTION styx_immutable_observation_presentation()
RETURNS trigger AS $$
BEGIN
    IF NEW.snapshot_token IS DISTINCT FROM OLD.snapshot_token OR
       NEW.consequence_id IS DISTINCT FROM OLD.consequence_id OR
       NEW.agent_id IS DISTINCT FROM OLD.agent_id OR
       NEW.lease_expires_at IS DISTINCT FROM OLD.lease_expires_at OR
       NEW.presented_at IS DISTINCT FROM OLD.presented_at OR
       NEW.presented_payload IS DISTINCT FROM OLD.presented_payload OR
       NEW.payload_hash IS DISTINCT FROM OLD.payload_hash OR
       NEW.presentation_version IS DISTINCT FROM OLD.presentation_version
    THEN
        RAISE EXCEPTION 'observation presentation is immutable'
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS cognitive_presentations_immutable
    ON cognitive_presentations;
CREATE TRIGGER cognitive_presentations_immutable
BEFORE UPDATE ON cognitive_presentations
FOR EACH ROW EXECUTE FUNCTION styx_immutable_observation_presentation();
