-- Wave 42: scoped social evidence. No global person/consciousness flags.

CREATE TABLE social_actors (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_agent_id text NOT NULL,
    identity_namespace text NOT NULL,
    actor_key text NOT NULL,
    actor_kind text NOT NULL CHECK (actor_kind IN
        ('local_agent','external_agent','human','collective','unknown')),
    attestation_principal_id text,
    private_label text,
    identity_evidence_hash text NOT NULL CHECK (identity_evidence_hash ~ '^[0-9a-f]{64}$'),
    payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','merged','retired')),
    superseded_by uuid,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (owner_agent_id,identity_namespace,actor_key),
    UNIQUE (id,owner_agent_id),
    UNIQUE (id,owner_agent_id,attestation_principal_id),
    CHECK (length(identity_namespace) BETWEEN 1 AND 128),
    CHECK (length(actor_key) BETWEEN 1 AND 256),
    CHECK (private_label IS NULL OR length(private_label) <= 256),
    CHECK (attestation_principal_id IS NULL OR
        length(attestation_principal_id) BETWEEN 1 AND 128),
    FOREIGN KEY (superseded_by,owner_agent_id) REFERENCES social_actors(id,owner_agent_id)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE social_identity_operations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_agent_id text NOT NULL,
    operation_key text NOT NULL,
    operation_kind text NOT NULL CHECK (operation_kind IN ('merge','unmerge','retire')),
    source_actor_id uuid NOT NULL,
    target_actor_id uuid,
    evidence_hash text NOT NULL CHECK (evidence_hash ~ '^[0-9a-f]{64}$'),
    payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (owner_agent_id,operation_key),
    FOREIGN KEY (source_actor_id,owner_agent_id) REFERENCES social_actors(id,owner_agent_id),
    FOREIGN KEY (target_actor_id,owner_agent_id) REFERENCES social_actors(id,owner_agent_id)
);

CREATE TABLE social_scopes (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_agent_id text NOT NULL,
    scope_key text NOT NULL,
    protocol_id text NOT NULL,
    protocol_version text NOT NULL,
    policy_hash text NOT NULL CHECK (policy_hash ~ '^[0-9a-f]{64}$'),
    created_by_principal_id text NOT NULL,
    payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','dissolved')),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    dissolved_at timestamptz,
    UNIQUE (owner_agent_id,scope_key),
    UNIQUE (id,owner_agent_id),
    CHECK (length(scope_key) BETWEEN 1 AND 256),
    CHECK (length(protocol_id) BETWEEN 1 AND 128),
    CHECK (length(protocol_version) BETWEEN 1 AND 64),
    CHECK (length(created_by_principal_id) BETWEEN 1 AND 128),
    CHECK ((status='dissolved')=(dissolved_at IS NOT NULL))
);

CREATE TABLE social_encounters (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_agent_id text NOT NULL,
    encounter_key text NOT NULL,
    scope_id uuid NOT NULL,
    observer_actor_id uuid NOT NULL,
    encountered_actor_id uuid NOT NULL,
    direction text NOT NULL CHECK (direction IN ('inbound','outbound','bidirectional')),
    channel_kind text NOT NULL,
    source_act_id uuid,
    source_observation_id uuid,
    summary text,
    evidence_hash text NOT NULL CHECK (evidence_hash ~ '^[0-9a-f]{64}$'),
    payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    confidence real NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    publisher_principal_id text NOT NULL,
    sequence bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (owner_agent_id,encounter_key),
    UNIQUE (id,owner_agent_id),
    CHECK (observer_actor_id<>encountered_actor_id),
    CHECK (length(channel_kind) BETWEEN 1 AND 64),
    CHECK (summary IS NULL OR length(summary)<=1000),
    CHECK (length(publisher_principal_id) BETWEEN 1 AND 128),
    CHECK (source_act_id IS NOT NULL OR source_observation_id IS NOT NULL),
    FOREIGN KEY (scope_id,owner_agent_id) REFERENCES social_scopes(id,owner_agent_id),
    FOREIGN KEY (observer_actor_id,owner_agent_id) REFERENCES social_actors(id,owner_agent_id),
    FOREIGN KEY (encountered_actor_id,owner_agent_id) REFERENCES social_actors(id,owner_agent_id),
    FOREIGN KEY (source_act_id,owner_agent_id) REFERENCES cognitive_acts(id,agent_id),
    FOREIGN KEY (source_observation_id,owner_agent_id)
        REFERENCES cognitive_consequences(id,agent_id)
);

CREATE TABLE social_attestations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_agent_id text NOT NULL,
    scope_id uuid NOT NULL,
    issuer_actor_id uuid NOT NULL,
    subject_actor_id uuid NOT NULL,
    attestation_key text NOT NULL,
    attestation_kind text NOT NULL DEFAULT 'direct' CHECK
        (attestation_kind IN ('direct','self','revocation','reported')),
    verdict text NOT NULL CHECK (verdict IN ('positive','negative','undetermined')),
    protocol_id text NOT NULL,
    protocol_version text NOT NULL,
    source_act_id uuid,
    source_action_ordinal integer,
    evidence_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
    payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    trust_level text NOT NULL CHECK (trust_level IN ('verified','unverified')),
    signature_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    supersedes_attestation_id uuid,
    issuer_principal_id text NOT NULL,
    sequence bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (owner_agent_id,scope_id,issuer_actor_id,attestation_key),
    UNIQUE (id,owner_agent_id),
    CHECK ((issuer_actor_id=subject_actor_id)=(attestation_kind='self')),
    CHECK (source_act_id IS NOT NULL),
    CHECK (attestation_kind<>'revocation' OR supersedes_attestation_id IS NOT NULL),
    CHECK (source_action_ordinal IS NULL OR source_action_ordinal>=0),
    CHECK (jsonb_typeof(evidence_refs)='array' AND jsonb_array_length(evidence_refs)<=16),
    CHECK (jsonb_typeof(signature_metadata)='object'),
    FOREIGN KEY (scope_id,owner_agent_id) REFERENCES social_scopes(id,owner_agent_id),
    FOREIGN KEY (issuer_actor_id,owner_agent_id) REFERENCES social_actors(id,owner_agent_id),
    FOREIGN KEY (issuer_actor_id,owner_agent_id,issuer_principal_id)
        REFERENCES social_actors(id,owner_agent_id,attestation_principal_id),
    FOREIGN KEY (subject_actor_id,owner_agent_id) REFERENCES social_actors(id,owner_agent_id),
    FOREIGN KEY (source_act_id,owner_agent_id) REFERENCES cognitive_acts(id,agent_id),
    FOREIGN KEY (source_act_id,source_action_ordinal)
        REFERENCES cognitive_actions(act_id,ordinal),
    FOREIGN KEY (supersedes_attestation_id,owner_agent_id)
        REFERENCES social_attestations(id,owner_agent_id)
);

CREATE TABLE social_pair_projections (
    owner_agent_id text NOT NULL,
    scope_id uuid NOT NULL,
    actor_low_id uuid NOT NULL,
    actor_high_id uuid NOT NULL,
    projection_version bigint NOT NULL CHECK (projection_version>=1),
    status text NOT NULL CHECK (status IN
        ('mutual_positive','mutual_denied','unilateral','undetermined','scope_dissolved')),
    low_to_high_attestation_id uuid,
    high_to_low_attestation_id uuid,
    policy_hash text NOT NULL CHECK (policy_hash ~ '^[0-9a-f]{64}$'),
    computed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY (owner_agent_id,scope_id,actor_low_id,actor_high_id),
    CHECK (actor_low_id::text < actor_high_id::text),
    FOREIGN KEY (scope_id,owner_agent_id) REFERENCES social_scopes(id,owner_agent_id),
    FOREIGN KEY (actor_low_id,owner_agent_id) REFERENCES social_actors(id,owner_agent_id),
    FOREIGN KEY (actor_high_id,owner_agent_id) REFERENCES social_actors(id,owner_agent_id),
    FOREIGN KEY (low_to_high_attestation_id,owner_agent_id)
        REFERENCES social_attestations(id,owner_agent_id),
    FOREIGN KEY (high_to_low_attestation_id,owner_agent_id)
        REFERENCES social_attestations(id,owner_agent_id)
);

CREATE TABLE social_visibility_grants (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_agent_id text NOT NULL,
    grant_key text NOT NULL,
    scope_id uuid NOT NULL,
    grantee_principal_id text NOT NULL,
    capability text NOT NULL CHECK (capability IN ('social:read','social:encounter')),
    evidence_class text NOT NULL CHECK (evidence_class IN
        ('actor','encounter','attestation','projection')),
    evidence_id uuid,
    actor_low_id uuid,
    actor_high_id uuid,
    issuer_principal_id text NOT NULL,
    expires_at timestamptz,
    payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (owner_agent_id,grant_key),
    UNIQUE (id,owner_agent_id),
    CHECK (length(grantee_principal_id) BETWEEN 1 AND 128),
    CHECK (length(issuer_principal_id) BETWEEN 1 AND 128),
    CHECK (
        (capability='social:encounter' AND evidence_class='encounter'
            AND evidence_id IS NULL AND actor_low_id IS NULL AND actor_high_id IS NULL)
        OR
        (capability='social:read' AND evidence_class<>'projection'
            AND evidence_id IS NOT NULL AND actor_low_id IS NULL AND actor_high_id IS NULL)
        OR
        (capability='social:read' AND evidence_class='projection'
            AND evidence_id IS NULL AND actor_low_id IS NOT NULL AND actor_high_id IS NOT NULL
            AND actor_low_id::text < actor_high_id::text)
    ),
    FOREIGN KEY (scope_id,owner_agent_id) REFERENCES social_scopes(id,owner_agent_id),
    FOREIGN KEY (actor_low_id,owner_agent_id) REFERENCES social_actors(id,owner_agent_id),
    FOREIGN KEY (actor_high_id,owner_agent_id) REFERENCES social_actors(id,owner_agent_id)
);

CREATE TABLE social_scope_operations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_agent_id text NOT NULL,
    scope_id uuid NOT NULL,
    operation_kind text NOT NULL CHECK (operation_kind='dissolve'),
    issuer_principal_id text NOT NULL,
    payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (owner_agent_id,scope_id,operation_kind),
    CHECK (length(issuer_principal_id) BETWEEN 1 AND 128),
    FOREIGN KEY (scope_id,owner_agent_id) REFERENCES social_scopes(id,owner_agent_id)
);

CREATE TABLE social_grant_operations (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_agent_id text NOT NULL,
    operation_key text NOT NULL,
    operation_kind text NOT NULL CHECK (operation_kind='revoke'),
    grant_id uuid NOT NULL,
    issuer_principal_id text NOT NULL,
    payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (owner_agent_id,operation_key),
    CHECK (length(operation_key) BETWEEN 1 AND 256),
    CHECK (length(issuer_principal_id) BETWEEN 1 AND 128),
    FOREIGN KEY (grant_id,owner_agent_id)
        REFERENCES social_visibility_grants(id,owner_agent_id)
);

CREATE TABLE social_delivery_receipts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_agent_id text NOT NULL,
    delivery_key text NOT NULL,
    scope_id uuid NOT NULL,
    attestation_id uuid,
    encounter_id uuid,
    receiving_agent_id text NOT NULL,
    observation_id uuid NOT NULL,
    payload_hash text NOT NULL CHECK (payload_hash ~ '^[0-9a-f]{64}$'),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (owner_agent_id,delivery_key),
    CHECK ((attestation_id IS NOT NULL)::int+(encounter_id IS NOT NULL)::int=1),
    FOREIGN KEY (scope_id,owner_agent_id) REFERENCES social_scopes(id,owner_agent_id),
    FOREIGN KEY (attestation_id,owner_agent_id) REFERENCES social_attestations(id,owner_agent_id),
    FOREIGN KEY (encounter_id,owner_agent_id) REFERENCES social_encounters(id,owner_agent_id),
    FOREIGN KEY (observation_id,receiving_agent_id)
        REFERENCES cognitive_consequences(id,agent_id)
);

CREATE INDEX social_attestations_pair_idx ON social_attestations
    (owner_agent_id,scope_id,issuer_actor_id,subject_actor_id,sequence,id);
CREATE UNIQUE INDEX social_attestations_single_revision_uq ON social_attestations
    (owner_agent_id,supersedes_attestation_id) WHERE supersedes_attestation_id IS NOT NULL;
CREATE INDEX social_encounters_scope_idx ON social_encounters(owner_agent_id,scope_id,created_at);
CREATE INDEX social_grants_lookup_idx ON social_visibility_grants
    (owner_agent_id,scope_id,grantee_principal_id,capability,evidence_class,
     evidence_id,actor_low_id,actor_high_id)
    WHERE revoked_at IS NULL;
CREATE INDEX social_delivery_receipts_receiver_idx ON social_delivery_receipts
    (receiving_agent_id,created_at);

CREATE OR REPLACE FUNCTION styx_social_append_only() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'social evidence ledger is append-only'
    USING ERRCODE='integrity_constraint_violation';
END; $$ LANGUAGE plpgsql;

CREATE TRIGGER social_encounters_append_only BEFORE UPDATE OR DELETE ON social_encounters
FOR EACH ROW EXECUTE FUNCTION styx_social_append_only();
CREATE TRIGGER social_attestations_append_only BEFORE UPDATE OR DELETE ON social_attestations
FOR EACH ROW EXECUTE FUNCTION styx_social_append_only();
CREATE TRIGGER social_identity_operations_append_only BEFORE UPDATE OR DELETE ON social_identity_operations
FOR EACH ROW EXECUTE FUNCTION styx_social_append_only();
CREATE TRIGGER social_delivery_receipts_append_only BEFORE UPDATE OR DELETE ON social_delivery_receipts
FOR EACH ROW EXECUTE FUNCTION styx_social_append_only();
CREATE TRIGGER social_scope_operations_append_only BEFORE UPDATE OR DELETE ON social_scope_operations
FOR EACH ROW EXECUTE FUNCTION styx_social_append_only();
CREATE TRIGGER social_grant_operations_append_only BEFORE UPDATE OR DELETE ON social_grant_operations
FOR EACH ROW EXECUTE FUNCTION styx_social_append_only();
